[build-system]
requires = ["setuptools>=70", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "target-finder-toolkit"
version = "0.2.0"
description = "Widget detection and interaction techniques: Bubble Cursor and Semantic Pointing"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

dependencies = [
  "numpy",
  "opencv-python",
  "mss",
  "ultralytics>=8.4.37",  # Version for YOLO26 support
  "PyQt6",
  "pyautogui",
  "pynput",
]

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "License :: OSI Approved :: MIT License",
]
keywords = ["yolo", "gui", "widgets", "detection", "hci"]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-qt",
    "pillow",
]
macos = [
    "pyobjc-framework-Quartz>=10.0",
    "pyobjc-framework-Cocoa>=10.0",
]

[project.scripts]
targetfinder-gui = "target_finder_toolkit.targetfinder:main"
bubblecursor     = "target_finder_toolkit.bubblecursor:main"
bubblegazelens   = "target_finder_toolkit.bubblegazelens:main"
semanticpointing = "target_finder_toolkit.semanticpointing:main"

[project.urls]
Repository = "https://github.com/ahmedbenakouche/target_finder_toolkit"
Documentation = "https://target-finder-toolkit.netlify.app/"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"target_finder_toolkit" = ["models/*.pt"]

[tool.setuptools.packages.find]
where = ["."]
include = ["target_finder_toolkit*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
